//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom position.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("CustomPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by classes.
        /// </summary>
        internal static string FilterByClasses {
            get {
                return ResourceManager.GetString("FilterByClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild name.
        /// </summary>
        internal static string GuildName {
            get {
                return ResourceManager.GetString("GuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild statistic.
        /// </summary>
        internal static string GuildStat {
            get {
                return ResourceManager.GetString("GuildStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors for player relation.
        /// </summary>
        internal static string RelationColors {
            get {
                return ResourceManager.GetString("RelationColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Guild.
        /// </summary>
        internal static string SelectedGuildName {
            get {
                return ResourceManager.GetString("SelectedGuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for filter by class            .
        /// </summary>
        internal static string SetFilterByClass {
            get {
                return ResourceManager.GetString("SetFilterByClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfomance test.
        /// </summary>
        internal static string ShowFPS {
            get {
                return ResourceManager.GetString("ShowFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show nicknames.
        /// </summary>
        internal static string ShowNicknames {
            get {
                return ResourceManager.GetString("ShowNicknames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only enemy players.
        /// </summary>
        internal static string ShowOnlyEnemy {
            get {
                return ResourceManager.GetString("ShowOnlyEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        internal static string TopRight {
            get {
                return ResourceManager.GetString("TopRight", resourceCulture);
            }
        }
    }
}
